export const ConfirmModal = ({
  isOpen,
  title,
  message,
  onConfirm,
  onCancel,
}) => {
  if (!isOpen) return null;

  return (
    <div
      className="
        fixed
        inset-0
        bg-black/50
        flex
        items-center
        justify-center
        z-50
        p-4
      "
    >
      <div
        className="
          bg-white
          dark:bg-slate-800
          rounded-xl
          shadow-xl
          w-full
          max-w-md
          p-6
        "
      >
        <h2
          className="
            text-xl
            font-bold
            mb-3
            text-slate-800
            dark:text-white
          "
        >
          {title}
        </h2>

        <p
          className="
            text-slate-600
            dark:text-slate-300
            mb-6
          "
        >
          {message}
        </p>

        <div
          className="
            flex
            justify-end
            gap-3
          "
        >
          <button
            onClick={onCancel}
            className="
              px-4
              py-2
              rounded-lg
              bg-slate-200
              hover:bg-slate-300
              transition
            "
          >
            Cancelar
          </button>

          <button
            onClick={onConfirm}
            className="
              px-4
              py-2
              rounded-lg
              bg-red-600
              text-white
              hover:bg-red-700
              transition
            "
          >
            Eliminar
          </button>
        </div>
      </div>
    </div>
  );
};